/**
 * ConversationHistoryService — lightweight log of completed mind conversations.
 *
 * Records the one-line "shape" of each call/chat so UserContextService can
 * surface "recently talked to X" context to the next conversation. The shape
 * is generated by a single Haiku call at conversation end and cached per
 * conversation id — never recomputed.
 *
 * Records are called fire-and-forget from TalkScreen / ChatScreen's close
 * path. All flag-gated: under ff_new_minds_system OFF, this service is a
 * no-op and the log stays empty.
 */

import AsyncStorage from '@react-native-async-storage/async-storage';
import { claudeProxy } from './AIProxy';
import { FeatureFlagsService } from './FeatureFlagsService';
import type { UserContextRecentMind } from '../types';

const LOG_KEY = 'conversation_history';
const MAX_RECORDS = 50;

interface ConversationRecord {
  id: string;                 // conv_<mindId>_<startedAt>
  mindId: string;             // 'companion' for null-persona (can't store null as JSON key)
  startedAt: number;
  endedAt: number;
  conversationShape: string;  // already-summarized, cached
}

// Minimal message shape — don't depend on ConversationService's full type.
export interface RecordableMessage {
  role: 'user' | 'assistant';
  text: string;
}

// ── Storage ──────────────────────────────────────────────────────────────────

async function readLog(): Promise<ConversationRecord[]> {
  try {
    const raw = await AsyncStorage.getItem(LOG_KEY);
    return raw ? JSON.parse(raw) : [];
  } catch {
    return [];
  }
}

async function writeLog(records: ConversationRecord[]): Promise<void> {
  try {
    const capped = records.length > MAX_RECORDS ? records.slice(-MAX_RECORDS) : records;
    await AsyncStorage.setItem(LOG_KEY, JSON.stringify(capped));
  } catch { /* non-fatal */ }
}

// ── Shape summarization ──────────────────────────────────────────────────────

async function summarizeShape(messages: RecordableMessage[]): Promise<string> {
  // Keep the prompt + transcript tight so the call stays cheap.
  const transcript = messages
    .slice(-20) // last 20 turns is plenty for shape
    .map(m => `${m.role === 'user' ? 'You' : 'Mind'}: ${m.text.trim()}`)
    .filter(l => l.length > 3)
    .join('\n')
    .slice(0, 3500);

  if (transcript.length < 40) return 'A brief exchange.';

  try {
    const response = await claudeProxy.messages.create({
      model: 'claude-haiku-4-5',
      max_tokens: 60,
      system:
        'You are summarizing the SHAPE of a conversation in ONE short sentence ' +
        '(max 14 words). Describe what the conversation was about in a tentative, ' +
        'observational tone — no advice, no analysis, no naming the mind. Example ' +
        'good outputs: "Sitting with a work decision that keeps looping." / ' +
        '"An uncertain conversation about a friendship fading."\n' +
        'Return ONLY the sentence, no preamble.',
      messages: [{ role: 'user', content: transcript }],
    });
    const text = response.content
      .filter((b: any) => b.type === 'text')
      .map((b: any) => b.text)
      .join('')
      .trim()
      .replace(/^["']|["']$/g, '');
    if (!text) return 'A brief exchange.';
    // Cap to 120 chars as an additional safety.
    return text.length > 120 ? text.slice(0, 117) + '…' : text;
  } catch {
    return 'A brief exchange.';
  }
}

// ── Public API ───────────────────────────────────────────────────────────────

export interface RecordInput {
  mindId: string | null; // null => Companion
  messages: RecordableMessage[];
  startedAt: number;
  endedAt?: number;
}

/**
 * Record a completed conversation. No-op when ff_new_minds_system is off
 * or when the conversation was too brief (no user turns).
 */
export async function recordCompletedConversation(input: RecordInput): Promise<void> {
  try {
    const on = await FeatureFlagsService.getFlag('ff_new_minds_system').catch(() => false);
    if (!on) return;

    const userTurns = input.messages.filter(m => m.role === 'user').length;
    if (userTurns === 0) return;

    const mindKey = input.mindId ?? 'companion';
    const id = `conv_${mindKey}_${input.startedAt}`;

    // If this conversation was already recorded (belt-and-braces — the close
    // path might fire twice on fast-tap), don't re-call Haiku.
    const existing = await readLog();
    if (existing.some(r => r.id === id)) return;

    const shape = await summarizeShape(input.messages);
    const record: ConversationRecord = {
      id,
      mindId: mindKey,
      startedAt: input.startedAt,
      endedAt: input.endedAt ?? Date.now(),
      conversationShape: shape,
    };
    await writeLog([...existing, record]);
  } catch {
    // Best-effort — history is opportunistic, never critical.
  }
}

/**
 * Return the most recent conversation PER MIND within `windowDays`, newest
 * first, capped at `limit`. Used by UserContextService to build `recentMinds`.
 */
export async function getRecentMindConversations(
  windowDays = 30,
  limit = 5,
): Promise<UserContextRecentMind[]> {
  const cutoff = Date.now() - windowDays * 86_400_000;
  const all = (await readLog()).filter(r => r.endedAt >= cutoff);

  // Dedupe to most-recent-per-mind.
  const byMind = new Map<string, ConversationRecord>();
  for (const r of all) {
    const prev = byMind.get(r.mindId);
    if (!prev || r.endedAt > prev.endedAt) byMind.set(r.mindId, r);
  }

  return Array.from(byMind.values())
    .sort((a, b) => b.endedAt - a.endedAt)
    .slice(0, limit)
    .map(r => ({
      mindId: r.mindId,
      lastTalkedAt: r.endedAt,
      conversationShape: r.conversationShape,
    }));
}
