// Custom Expo config plugin that enables Android Auto Backup so user
// journal data (AsyncStorage-backed summaries, entries, intentions,
// settings) survives uninstall and is restored on reinstall when the
// same Google account is used.
//
// What this plugin does:
//   1. Writes `android:allowBackup="true"` on the <application> tag
//      (usually already true from Expo defaults, but we pin it here so a
//      future RN/Expo change can't silently turn it off).
//   2. Points the tag at two XML rule files:
//        - fullBackupContent      → backup_rules.xml         (API 23-30)
//        - dataExtractionRules    → data_extraction_rules.xml (API 31+)
//      Both XML files live in android/app/src/main/res/xml/ and carve
//      out the wisdom-image cache + WebView dbs so the backup stays
//      under Android's 25 MB cap.
//   3. Generates those XML files on every prebuild so `expo prebuild
//      --clean` doesn't wipe them.
//
// Why a plugin at all: without it the direct AndroidManifest.xml edit
// gets overwritten whenever Expo regenerates the android/ folder.
const { withAndroidManifest, withDangerousMod } = require('@expo/config-plugins');
const fs   = require('fs');
const path = require('path');

// ── Manifest attributes ─────────────────────────────────────────────────────

function withBackupManifest(config) {
  return withAndroidManifest(config, (androidConfig) => {
    const app = androidConfig.modResults.manifest.application?.[0];
    if (!app) return androidConfig;
    app.$['android:allowBackup']          = 'true';
    app.$['android:fullBackupContent']    = '@xml/backup_rules';
    app.$['android:dataExtractionRules']  = '@xml/data_extraction_rules';
    return androidConfig;
  });
}

// ── XML rule files — regenerated on every prebuild ──────────────────────────

const BACKUP_RULES_XML = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by plugins/withBackupRules.js — do not edit by hand. -->
<full-backup-content>
  <exclude domain="file" path="wisdom_images/" />
  <exclude domain="database" path="webview.db" />
  <exclude domain="database" path="webview.db-journal" />
  <exclude domain="database" path="webviewCookiesChromium.db" />
  <exclude domain="database" path="webviewCache.db" />
</full-backup-content>
`;

const DATA_EXTRACTION_RULES_XML = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by plugins/withBackupRules.js — do not edit by hand. -->
<data-extraction-rules>
  <cloud-backup>
    <exclude domain="file" path="wisdom_images/" />
    <exclude domain="database" path="webview.db" />
    <exclude domain="database" path="webview.db-journal" />
    <exclude domain="database" path="webviewCookiesChromium.db" />
    <exclude domain="database" path="webviewCache.db" />
  </cloud-backup>
  <device-transfer>
    <exclude domain="file" path="wisdom_images/" />
    <exclude domain="database" path="webview.db" />
    <exclude domain="database" path="webviewCache.db" />
  </device-transfer>
</data-extraction-rules>
`;

function withBackupRuleFiles(config) {
  return withDangerousMod(config, [
    'android',
    (dangerousConfig) => {
      const xmlDir = path.join(
        dangerousConfig.modRequest.platformProjectRoot,
        'app/src/main/res/xml',
      );
      fs.mkdirSync(xmlDir, { recursive: true });
      fs.writeFileSync(path.join(xmlDir, 'backup_rules.xml'), BACKUP_RULES_XML);
      fs.writeFileSync(path.join(xmlDir, 'data_extraction_rules.xml'), DATA_EXTRACTION_RULES_XML);
      return dangerousConfig;
    },
  ]);
}

module.exports = function withBackupRules(config) {
  config = withBackupManifest(config);
  config = withBackupRuleFiles(config);
  return config;
};
