/**
 * AddShortModal — simplified form to create a custom Wisdom Short.
 *
 * The user supplies only:
 *   • Title — a concise, inviting headline
 *   • Body  — 2–4 sentences of the insight itself
 *
 * Everything else (pullquote, author, source type, themes, emotional states,
 * cognitive patterns, values, enneagram resonance, depth, and the image
 * prompt) is auto-generated by Claude.  The card image is then generated by
 * DALL-E 3 and cached locally in the background after the modal closes.
 */

import React, { useState, useEffect } from 'react';
import {
  Modal, View, Text, TextInput, TouchableOpacity, StyleSheet,
  KeyboardAvoidingView, Platform, Alert, ActivityIndicator,
} from 'react-native';
import { Feather } from '@expo/vector-icons';
import { WisdomShort } from '../types';
import { StorageService } from '../services/StorageService';
import { autoFillShortMetadata, generateAndCacheImage } from '../services/WisdomImageService';

interface Props {
  visible: boolean;
  editShort?: WisdomShort | null;
  onClose: () => void;
  onSaved: (short: WisdomShort) => void;
}

const PH = 'rgba(152, 212, 250, 0.30)';

export default function AddShortModal({ visible, editShort, onClose, onSaved }: Props) {
  const [title,   setTitle]   = useState('');
  const [body,    setBody]    = useState('');
  const [saving,  setSaving]  = useState(false);
  const [phase,   setPhase]   = useState<'idle' | 'thinking' | 'painting'>('idle');

  // Pre-fill when editing an existing custom short
  useEffect(() => {
    if (!visible) return;
    if (editShort) {
      setTitle(editShort.title);
      setBody(editShort.short);
    } else {
      setTitle('');
      setBody('');
    }
    setPhase('idle');
  }, [visible, editShort?.id]);

  const handleSave = async () => {
    if (!title.trim() || !body.trim()) {
      Alert.alert('Required', 'Please enter both a title and the body text.');
      return;
    }

    setSaving(true);
    setPhase('thinking');

    try {
      const settings = await StorageService.getSettings();
      if (!settings?.anthropicApiKey) {
        Alert.alert('API key missing', 'Add your Anthropic API key in Settings to create wisdom shorts.');
        return;
      }

      // ── Step 1: Claude auto-fills all metadata ──────────────────────────────
      const meta = await autoFillShortMetadata(title.trim(), body.trim(), settings.anthropicApiKey);

      const id = editShort?.id ?? `custom_${Date.now()}_${Math.random().toString(36).slice(2, 6)}`;

      const wisdomShort: WisdomShort = {
        id,
        title:               title.trim(),
        short:               body.trim(),
        pullquote:           meta.pullquote,
        source_author:       meta.source_author,
        source_url:          '',
        source_type:         meta.source_type,
        themes:              meta.themes,
        emotional_states:    meta.emotional_states,
        cognitive_patterns:  meta.cognitive_patterns,
        values:              meta.values,
        enneagram_resonance: meta.enneagram_resonance,
        cognitive_style:     [],
        depth:               meta.depth,
        imagePrompt:         meta.imagePrompt,
      };

      // ── Step 2: Persist the short right away ────────────────────────────────
      await StorageService.saveCustomShort(wisdomShort);
      onSaved(wisdomShort);

      // ── Step 3: Generate card image in background (don't block close) ───────
      setPhase('painting');
      generateAndCacheImage(wisdomShort).catch(() => {});

      // Close after a brief moment so user sees the "painting" phase message
      setTimeout(() => {
        setSaving(false);
        setPhase('idle');
        setTitle('');
        setBody('');
        onClose();
      }, 600);

    } catch (e: any) {
      Alert.alert('Error', e?.message ?? 'Could not save the short. Please try again.');
      setSaving(false);
      setPhase('idle');
    }
  };

  const phaseLabel = phase === 'thinking' ? 'Claude is thinking…' : phase === 'painting' ? 'Painting the image…' : '';
  const canSave = title.trim().length > 0 && body.trim().length > 0 && !saving;

  return (
    <Modal visible={visible} animationType="slide" transparent onRequestClose={onClose}>
      <KeyboardAvoidingView
        style={styles.overlay}
        behavior={Platform.OS === 'ios' ? 'padding' : 'height'}
      >
        <TouchableOpacity style={styles.backdrop} activeOpacity={1} onPress={saving ? undefined : onClose} />

        <View style={styles.sheet}>

          {/* Header */}
          <View style={styles.header}>
            <TouchableOpacity onPress={saving ? undefined : onClose} style={styles.headerBtn}>
              <Text style={[styles.cancelText, saving && { opacity: 0.35 }]}>Cancel</Text>
            </TouchableOpacity>
            <Text style={styles.headerTitle}>{editShort ? 'Edit Short' : 'New Short'}</Text>
            <TouchableOpacity onPress={handleSave} disabled={!canSave} style={styles.headerBtn}>
              {saving
                ? <ActivityIndicator size="small" color="rgba(152, 212, 250, 0.80)" />
                : <Text style={[styles.saveText, !canSave && { opacity: 0.35 }]}>Publish</Text>
              }
            </TouchableOpacity>
          </View>

          {/* Phase status */}
          {saving && (
            <View style={styles.phaseRow}>
              <Feather name="zap" size={12} color="rgba(251,191,36,0.70)" />
              <Text style={styles.phaseText}>{phaseLabel}</Text>
            </View>
          )}

          {/* Subtitle */}
          {!saving && (
            <Text style={styles.subtitle}>
              Just share the idea. The app will handle the rest — pullquote, tags, and a bespoke image.
            </Text>
          )}

          {/* Title field */}
          <View style={styles.field}>
            <Text style={styles.fieldLabel}>Title</Text>
            <TextInput
              style={styles.input}
              value={title}
              onChangeText={setTitle}
              placeholder="e.g. The Harder You Try to Control, the Less You Have"
              placeholderTextColor={PH}
              multiline
              editable={!saving}
            />
          </View>

          {/* Body field */}
          <View style={[styles.field, { paddingBottom: 32 }]}>
            <Text style={styles.fieldLabel}>Body</Text>
            <Text style={styles.fieldHint}>2–4 sentences. The full insight.</Text>
            <TextInput
              style={[styles.input, styles.tall]}
              value={body}
              onChangeText={setBody}
              placeholder="Write the insight here…"
              placeholderTextColor={PH}
              multiline
              textAlignVertical="top"
              editable={!saving}
            />
          </View>

        </View>
      </KeyboardAvoidingView>
    </Modal>
  );
}

const styles = StyleSheet.create({
  overlay: { flex: 1, justifyContent: 'flex-end' },
  backdrop: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(0,0,0,0.75)' },

  sheet: {
    backgroundColor: '#040d1e',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    borderTopWidth: 1,
    borderTopColor: 'rgba(152, 212, 250, 0.18)',
    paddingHorizontal: 18,
    paddingTop: 0,
  },

  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: 18,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(152, 212, 250, 0.08)',
  },
  headerBtn: { minWidth: 64 },
  headerTitle: {
    fontSize: 16,
    fontWeight: '500',
    color: 'rgba(224, 242, 254, 0.95)',
    fontFamily: 'Baskerville',
  },
  cancelText: {
    color: 'rgba(152, 212, 250, 0.65)',
    fontSize: 15,
    fontFamily: 'GillSans-Light',
  },
  saveText: {
    color: 'rgba(152, 212, 250, 0.9)',
    fontSize: 15,
    fontWeight: '600',
    textAlign: 'right',
    fontFamily: 'GillSans-Light',
  },

  phaseRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 10,
    paddingHorizontal: 4,
  },
  phaseText: {
    fontSize: 13,
    color: 'rgba(251,191,36,0.75)',
    fontFamily: 'GillSans-Light',
    fontStyle: 'italic',
  },

  subtitle: {
    fontSize: 13,
    color: 'rgba(152,212,250,0.45)',
    lineHeight: 19,
    fontFamily: 'GillSans-Light',
    paddingTop: 10,
    paddingBottom: 6,
  },

  field: { marginTop: 14 },
  fieldLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: 'rgba(224, 242, 254, 0.8)',
    marginBottom: 4,
  },
  fieldHint: {
    fontSize: 11,
    color: 'rgba(152, 212, 250, 0.40)',
    marginBottom: 6,
    fontFamily: 'GillSans-Light',
  },

  input: {
    backgroundColor: 'rgba(152, 212, 250, 0.05)',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(152, 212, 250, 0.13)',
    color: 'rgba(224, 242, 254, 0.92)',
    fontSize: 14,
    paddingHorizontal: 12,
    paddingVertical: 10,
    lineHeight: 20,
    fontFamily: 'GillSans-Light',
  },
  tall: {
    minHeight: 120,
    textAlignVertical: 'top',
  },
});
